// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var ContactUs = exports.ContactUs = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineContactUs()

function defineContactUs () {
  var enc = [
    encodings.string
  ]

  ContactUs.encodingLength = encodingLength
  ContactUs.encode = encode
  ContactUs.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.email)) {
      var len = enc[0].encodingLength(obj.email)
      length += 1 + len
    }
    if (defined(obj.name)) {
      var len = enc[0].encodingLength(obj.name)
      length += 1 + len
    }
    if (defined(obj.msg)) {
      var len = enc[0].encodingLength(obj.msg)
      length += 1 + len
    }
    if (defined(obj.locale)) {
      var len = enc[0].encodingLength(obj.locale)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.email)) {
      buf[offset++] = 10
      enc[0].encode(obj.email, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.name)) {
      buf[offset++] = 18
      enc[0].encode(obj.name, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.msg)) {
      buf[offset++] = 26
      enc[0].encode(obj.msg, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.locale)) {
      buf[offset++] = 34
      enc[0].encode(obj.locale, buf, offset)
      offset += enc[0].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      email: "",
      name: "",
      msg: "",
      locale: ""
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.email = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 2:
        obj.name = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 3:
        obj.msg = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 4:
        obj.locale = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
