// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var Upload = exports.Upload = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineUpload()

function defineUpload () {
  var enc = [
    encodings.string
  ]

  Upload.encodingLength = encodingLength
  Upload.encode = encode
  Upload.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.name)) {
      var len = enc[0].encodingLength(obj.name)
      length += 1 + len
    }
    if (defined(obj.mimetype)) {
      var len = enc[0].encodingLength(obj.mimetype)
      length += 1 + len
    }
    if (defined(obj.data)) {
      var len = enc[0].encodingLength(obj.data)
      length += 1 + len
    }
    if (defined(obj.locale)) {
      var len = enc[0].encodingLength(obj.locale)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.name)) {
      buf[offset++] = 10
      enc[0].encode(obj.name, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.mimetype)) {
      buf[offset++] = 18
      enc[0].encode(obj.mimetype, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.data)) {
      buf[offset++] = 26
      enc[0].encode(obj.data, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.locale)) {
      buf[offset++] = 34
      enc[0].encode(obj.locale, buf, offset)
      offset += enc[0].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      name: "",
      mimetype: "",
      data: "",
      locale: ""
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.name = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 2:
        obj.mimetype = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 3:
        obj.data = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 4:
        obj.locale = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
