// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var DecoderTest = exports.DecoderTest = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineDecoderTest()

function defineDecoderTest () {
  var enc = [
    encodings.string,
    encodings.bool
  ]

  DecoderTest.encodingLength = encodingLength
  DecoderTest.encode = encode
  DecoderTest.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.action)) {
      var len = enc[0].encodingLength(obj.action)
      length += 1 + len
    }
    if (defined(obj.email)) {
      var len = enc[0].encodingLength(obj.email)
      length += 1 + len
    }
    if (defined(obj.password)) {
      var len = enc[0].encodingLength(obj.password)
      length += 1 + len
    }
    if (defined(obj.tosAgreement)) {
      var len = enc[1].encodingLength(obj.tosAgreement)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.action)) {
      buf[offset++] = 10
      enc[0].encode(obj.action, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.email)) {
      buf[offset++] = 18
      enc[0].encode(obj.email, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.password)) {
      buf[offset++] = 26
      enc[0].encode(obj.password, buf, offset)
      offset += enc[0].encode.bytes
    }
    if (defined(obj.tosAgreement)) {
      buf[offset++] = 32
      enc[1].encode(obj.tosAgreement, buf, offset)
      offset += enc[1].encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      action: "",
      email: "",
      password: "",
      tosAgreement: false
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.action = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 2:
        obj.email = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 3:
        obj.password = enc[0].decode(buf, offset)
        offset += enc[0].decode.bytes
        break
        case 4:
        obj.tosAgreement = enc[1].decode(buf, offset)
        offset += enc[1].decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
