export default {
  CONFIRM: 'CONFIRM',
  RESET: {
    CREATE: 'RESET_CREATE'
  },
  USER: {
    CREATE: 'USER_CREATE',
    CREATE_SOCIAL: 'USER_CREATE_SOCIAL',
    EDIT: 'USER_EDIT',
    DESTROY: 'USER_DESTROY',
    GET: 'USER_GET',
    CONFIRM_PHONE: 'USER_CONFIRM_PHONE',
    SET_ROLE: 'SET_ROLE'
  },
  TOKEN: {
    CREATE: 'TOKEN_CREATE',
    EXTEND: 'TOKEN_EXTEND',
    DESTROY: 'TOKEN_DESTROY',
    GET: 'TOKEN_GET'
  },
  REFER: {
    REFER: 'REFER_REFER',
    USE: 'REFER_USE',
    REGISTER: 'REFER_REGISTER'
  },
  SHOP: {
    PRODUCTS_GET: 'PRODUCTS_GET',
    PRODUCT_GET_BYID: 'PRODUCT_GET_BYID',
    CART_ADD: 'CART_ADD',
    CART_REMOVE: 'CART_REMOVE',
    CART_GET: 'CART_REMOVE',
    WISHLIST_ADD: 'WISHLIST_ADD',
    WISHLIST_REMOVE: 'WISHLIST_REMOVE',
    WISHLIST_GET: 'WISHLIST_GET',
    CHECKOUT: 'CHECKOUT'
  },
  BLOG: {
    ARTICLES_GET: 'BLOG_ARTICLES_GET',
    ARTICLE_GET_BYTITLE: 'BLOG_ARTICLE_GET_BYTITLE',
    ARTICLE_GET_BYCATEGORY: 'BLOG_ARTICLE_GET_BYCATEGORY',
    ARTICLE_ADD: 'BLOG_ARTICLE_ADD',
    ARTICLE_EDIT: 'BLOG_ARTICLE_EDIT',
    ARTICLE_DELETE: 'BLOG_ARTICLE_DELETE',
    CATEGORY_ADD: 'BLOG_CATEGORY_ADD',
    CATEGORY_EDIT: 'BLOG_CATEGORY_EDIT',
    CATEGORY_DELETE: 'BLOG_CATEGORY_DELETE',
    CATEGORIES_GET: 'BLOG_CATEGORIES_GET'
  },
  UPLOAD: 'UPLOAD',
  CONTACT_US: 'CONTACT_US',
  MODULE: {
    CREATE: 'MODULE_CREATE',
    MIGRATE: 'MODULE_MIGRATE'
  },
  NOT_FOUND: 'NOT_FOUND',
  NOTIFY: {
    PUSH: 'NOTIFY',
    SUBSCRIBE: 'NOTIFY_SUBSCRIBE'
  }
}
