import { promisify } from 'util'
import { object, string } from 'yup'

import { validEmail } from '../utils'
import { t } from '../translations'
import { LANGUAGES  } from '../../config'

export const countriesSchema = {
  title: 'Countries schema v.1.0',
  type: 'array',
  required: ['key', 'country'],
  properties: {
    key: {
      type: 'string',
      uniqueItems: true,
      maxLength: 2,
      minLength: 2
    },
    country: {
      type: 'string',
      uniqueItems: true
    }
  }
}

export const countries = [
  { key: '', country: '' },
  { key: 'af', country: 'Afghanistan' },
  { key: 'ax', country: 'Åland Islands' },
  { key: 'al', country: 'Albania' },
  { key: 'dz', country: 'Algeria' },
  { key: 'as', country: 'American Samoa' },
  { key: 'ad', country: 'Andorra' },
  { key: 'ao', country: 'Angola' },
  { key: 'ai', country: 'Anguilla' },
  { key: 'aq', country: 'Antarctica' },
  { key: 'ag', country: 'Antigua and Barbuda' },
  { key: 'ar', country: 'Argentina' },
  { key: 'am', country: 'Armenia' },
  { key: 'aw', country: 'Aruba' },
  { key: 'au', country: 'Australia' },
  { key: 'at', country: 'Austria' },
  { key: 'az', country: 'Azerbaijan' },
  { key: 'bs', country: 'Bahamas' },
  { key: 'bh', country: 'Bahrain' },
  { key: 'bd', country: 'Bangladesh' },
  { key: 'bb', country: 'Barbados' },
  { key: 'by', country: 'Belarus' },
  { key: 'be', country: 'Belgium' },
  { key: 'bz', country: 'Belize' },
  { key: 'bj', country: 'Benin' },
  { key: 'bm', country: 'Bermuda' },
  { key: 'bt', country: 'Bhutan' },
  { key: 'bo', country: 'Bolivia (Plurinational State of)' },
  { key: 'bq', country: 'Bonaire, Sint Eustatius and Saba' },
  { key: 'ba', country: 'Bosnia and Herzegovina' },
  { key: 'bw', country: 'Botswana' },
  { key: 'bv', country: 'Bouvet Island' },
  { key: 'br', country: 'Brazil' },
  { key: 'io', country: 'British Indian Ocean Territory' },
  { key: 'bn', country: 'Brunei Darussalam' },
  { key: 'bg', country: 'Bulgaria' },
  { key: 'bf', country: 'Burkina Faso' },
  { key: 'bi', country: 'Burundi' },
  { key: 'kh', country: 'Cambodia' },
  { key: 'cm', country: 'Cameroon' },
  { key: 'ca', country: 'Canada' },
  { key: 'cv', country: 'Cabo Verde' },
  { key: 'ky', country: 'Cayman Islands' },
  { key: 'cf', country: 'Central African Republic' },
  { key: 'td', country: 'Chad' },
  { key: 'cl', country: 'Chile' },
  { key: 'cn', country: 'China' },
  { key: 'cx', country: 'Christmas Island' },
  { key: 'cc', country: 'Cocos (Keeling) Islands' },
  { key: 'co', country: 'Colombia' },
  { key: 'km', country: 'Comoros' },
  { key: 'cg', country: 'Congo' },
  { key: 'cd', country: 'Congo (Democratic Republic of the)' },
  { key: 'ck', country: 'Cook Islands' },
  { key: 'cr', country: 'Costa Rica' },
  { key: 'ci', country: 'Côte d\'Ivoire' },
  { key: 'hr', country: 'Croatia' },
  { key: 'cu', country: 'Cuba' },
  { key: 'cw', country: 'Curaçao' },
  { key: 'cy', country: 'Cyprus' },
  { key: 'cz', country: 'Czech Republic' },
  { key: 'dk', country: 'Denmark' },
  { key: 'dj', country: 'Djibouti' },
  { key: 'dm', country: 'Dominica' },
  { key: 'do', country: 'Dominican Republic' },
  { key: 'ec', country: 'Ecuador' },
  { key: 'eg', country: 'Egypt' },
  { key: 'sv', country: 'El Salvador' },
  { key: 'gq', country: 'Equatorial Guinea' },
  { key: 'er', country: 'Eritrea' },
  { key: 'ee', country: 'Estonia' },
  { key: 'et', country: 'Ethiopia' },
  { key: 'eu', country: 'European Union' },
  { key: 'fk', country: 'Falkland Islands (Malvinas)' },
  { key: 'fo', country: 'Faroe Islands' },
  { key: 'fj', country: 'Fiji' },
  { key: 'fi', country: 'Finland' },
  { key: 'fr', country: 'France' },
  { key: 'gf', country: 'French Guiana' },
  { key: 'pf', country: 'French Polynesia' },
  { key: 'tf', country: 'French Southern Territories' },
  { key: 'ga', country: 'Gabon' },
  { key: 'gm', country: 'Gambia' },
  { key: 'ge', country: 'Georgia' },
  { key: 'de', country: 'Germany' },
  { key: 'gh', country: 'Ghana' },
  { key: 'gi', country: 'Gibraltar' },
  { key: 'gr', country: 'Greece' },
  { key: 'gl', country: 'Greenland' },
  { key: 'gd', country: 'Grenada' },
  { key: 'gp', country: 'Guadeloupe' },
  { key: 'gu', country: 'Guam' },
  { key: 'gt', country: 'Guatemala' },
  { key: 'gg', country: 'Guernsey' },
  { key: 'gn', country: 'Guinea' },
  { key: 'gw', country: 'Guinea-Bissau' },
  { key: 'gy', country: 'Guyana' },
  { key: 'ht', country: 'Haiti' },
  { key: 'hm', country: 'Heard Island and McDonald Islands' },
  { key: 'va', country: 'Holy See' },
  { key: 'hn', country: 'Honduras' },
  { key: 'hk', country: 'Hong Kong' },
  { key: 'hu', country: 'Hungary' },
  { key: 'is', country: 'Iceland' },
  { key: 'in', country: 'India' },
  { key: 'id', country: 'Indonesia' },
  { key: 'ir', country: 'Iran (Islamic Republic of)' },
  { key: 'iq', country: 'Iraq' },
  { key: 'ie', country: 'Ireland' },
  { key: 'im', country: 'Isle of Man' },
  { key: 'il', country: 'Israel' },
  { key: 'it', country: 'Italy' },
  { key: 'jm', country: 'Jamaica' },
  { key: 'jp', country: 'Japan' },
  { key: 'je', country: 'Jersey' },
  { key: 'jo', country: 'Jordan' },
  { key: 'kz', country: 'Kazakhstan' },
  { key: 'ke', country: 'Kenya' },
  { key: 'ki', country: 'Kiribati' },
  { key: 'kp', country: 'Korea (Democratic People\'s Republic of)' },
  { key: 'kr', country: 'Korea (Republic of)' },
  { key: 'kw', country: 'Kuwait' },
  { key: 'kg', country: 'Kyrgyzstan' },
  { key: 'la', country: 'Lao People\'s Democratic Republic' },
  { key: 'lv', country: 'Latvia' },
  { key: 'lb', country: 'Lebanon' },
  { key: 'ls', country: 'Lesotho' },
  { key: 'lr', country: 'Liberia' },
  { key: 'ly', country: 'Libya' },
  { key: 'li', country: 'Liechtenstein' },
  { key: 'lt', country: 'Lithuania' },
  { key: 'lu', country: 'Luxembourg' },
  { key: 'mo', country: 'Macao' },
  { key: 'mk', country: 'Macedonia (the former Yugoslav Republic of)' },
  { key: 'mg', country: 'Madagascar' },
  { key: 'mw', country: 'Malawi' },
  { key: 'my', country: 'Malaysia' },
  { key: 'mv', country: 'Maldives' },
  { key: 'ml', country: 'Mali' },
  { key: 'mt', country: 'Malta' },
  { key: 'mh', country: 'Marshall Islands' },
  { key: 'mq', country: 'Martinique' },
  { key: 'mr', country: 'Mauritania' },
  { key: 'mu', country: 'Mauritius' },
  { key: 'yt', country: 'Mayotte' },
  { key: 'mx', country: 'Mexico' },
  { key: 'fm', country: 'Micronesia (Federated States of)' },
  { key: 'md', country: 'Moldova (Republic of)' },
  { key: 'mc', country: 'Monaco' },
  { key: 'mn', country: 'Mongolia' },
  { key: 'me', country: 'Montenegro' },
  { key: 'ms', country: 'Montserrat' },
  { key: 'ma', country: 'Morocco' },
  { key: 'mz', country: 'Mozambique' },
  { key: 'mm', country: 'Myanmar' },
  { key: 'na', country: 'Namibia' },
  { key: 'nr', country: 'Nauru' },
  { key: 'np', country: 'Nepal' },
  { key: 'nl', country: 'Netherlands' },
  { key: 'nc', country: 'New Caledonia' },
  { key: 'nz', country: 'New Zealand' },
  { key: 'ni', country: 'Nicaragua' },
  { key: 'ne', country: 'Niger' },
  { key: 'ng', country: 'Nigeria' },
  { key: 'nu', country: 'Niue' },
  { key: 'nf', country: 'Norfolk Island' },
  { key: 'mp', country: 'Northern Mariana Islands' },
  { key: 'no', country: 'Norway' },
  { key: 'om', country: 'Oman' },
  { key: 'pk', country: 'Pakistan' },
  { key: 'pw', country: 'Palau' },
  { key: 'ps', country: 'Palestine, State of' },
  { key: 'pa', country: 'Panama' },
  { key: 'pg', country: 'Papua New Guinea' },
  { key: 'py', country: 'Paraguay' },
  { key: 'pe', country: 'Peru' },
  { key: 'ph', country: 'Philippines' },
  { key: 'pn', country: 'Pitcairn' },
  { key: 'pl', country: 'Poland' },
  { key: 'pt', country: 'Portugal' },
  { key: 'pr', country: 'Puerto Rico' },
  { key: 'qa', country: 'Qatar' },
  { key: 're', country: 'Réunion' },
  { key: 'ro', country: 'Romania' },
  { key: 'ru', country: 'Russian Federation' },
  { key: 'rw', country: 'Rwanda' },
  { key: 'bl', country: 'Saint Barthélemy' },
  { key: 'sh', country: 'Saint Helena, Ascension and Tristan da Cunha' },
  { key: 'kn', country: 'Saint Kitts and Nevis' },
  { key: 'lc', country: 'Saint Lucia' },
  { key: 'mf', country: 'Saint Martin (French part)' },
  { key: 'pm', country: 'Saint Pierre and Miquelon' },
  { key: 'vc', country: 'Saint Vincent and the Grenadines' },
  { key: 'ws', country: 'Samoa' },
  { key: 'sm', country: 'San Marino' },
  { key: 'st', country: 'Sao Tome and Principe' },
  { key: 'sa', country: 'Saudi Arabia' },
  { key: 'sn', country: 'Senegal' },
  { key: 'rs', country: 'Serbia' },
  { key: 'sc', country: 'Seychelles' },
  { key: 'sl', country: 'Sierra Leone' },
  { key: 'sg', country: 'Singapore' },
  { key: 'sx', country: 'Sint Maarten (Dutch part)' },
  { key: 'sk', country: 'Slovakia' },
  { key: 'si', country: 'Slovenia' },
  { key: 'sb', country: 'Solomon Islands' },
  { key: 'so', country: 'Somalia' },
  { key: 'za', country: 'South Africa' },
  { key: 'gs', country: 'South Georgia and the South Sandwich Islands' },
  { key: 'ss', country: 'South Sudan' },
  { key: 'es', country: 'Spain' },
  { key: 'lk', country: 'Sri Lanka' },
  { key: 'sd', country: 'Sudan' },
  { key: 'sr', country: 'Suriname' },
  { key: 'sj', country: 'Svalbard and Jan Mayen' },
  { key: 'sz', country: 'Swaziland' },
  { key: 'se', country: 'Sweden' },
  { key: 'ch', country: 'Switzerland' },
  { key: 'sy', country: 'Syrian Arab Republic' },
  { key: 'tw', country: 'Taiwan, Province of China' },
  { key: 'tj', country: 'Tajikistan' },
  { key: 'tz', country: 'Tanzania, United Republic of' },
  { key: 'th', country: 'Thailand' },
  { key: 'tl', country: 'Timor-Leste' },
  { key: 'tg', country: 'Togo' },
  { key: 'tk', country: 'Tokelau' },
  { key: 'to', country: 'Tonga' },
  { key: 'tt', country: 'Trinidad and Tobago' },
  { key: 'tn', country: 'Tunisia' },
  { key: 'tr', country: 'Turkey' },
  { key: 'tm', country: 'Turkmenistan' },
  { key: 'tc', country: 'Turks and Caicos Islands' },
  { key: 'tv', country: 'Tuvalu' },
  { key: 'ug', country: 'Uganda' },
  { key: 'ua', country: 'Ukraine' },
  { key: 'ae', country: 'United Arab Emirates' },
  { key: 'gb', country: 'United Kingdom' },
  { key: 'us', country: 'United States of America' },
  { key: 'um', country: 'United States Minor Outlying Islands' },
  { key: 'uy', country: 'Uruguay' },
  { key: 'uz', country: 'Uzbekistan' },
  { key: 'vu', country: 'Vanuatu' },
  { key: 've', country: 'Venezuela (Bolivarian Republic of)' },
  { key: 'vn', country: 'Viet Nam' },
  { key: 'vg', country: 'Virgin Islands (British)' },
  { key: 'vi', country: 'Virgin Islands (U.S.)' },
  { key: 'wf', country: 'Wallis and Futuna' },
  { key: 'eh', country: 'Western Sahara' },
  { key: 'ye', country: 'Yemen' },
  { key: 'zm', country: 'Zambia' },
  { key: 'zw', country: 'Zimbabwe' }
]

const userSchema = object().shape({
  password: string().transform((cv, ov) => ov === '' ? undefined : cv).min(12),
  firstName: string().transform((cv, ov) => ov === '' ? undefined : cv).min(3),
  lastName: string().transform((cv, ov) => ov === '' ? undefined : cv).min(3),
  phone: string().transform((cv, ov) => ov === '' ? undefined : cv).min(8),
  address: string().transform((cv, ov) => ov === '' ? undefined : cv).min(5),
  zipCode: string().transform((cv, ov) => ov === '' ? undefined : cv).min(5),
  city: string().transform((cv, ov) => ov === '' ? undefined : cv).min(3),
  country: string().transform((cv, ov) => ov === '' ? undefined : cv).length(2),
  dob: string().transform((cv, ov) => ov === '' ? undefined : cv),
  avatarUrl: string().transform((cv, ov) => ov === '' ? undefined : cv).url()
})

export const validUser = async (body) => {
  return await userSchema.isValid(body)
}

const _userObj = async (data, done) => {
  if (typeof data.body === 'object') {
    const _validEmail = await validEmail(data.body.email).catch((e) => done(e))
    if (_validEmail) {
      const _validUser = await validUser(data.body)
      if (_validUser) {
        data.body.email = _validEmail
        done(null, data.body)
      } else {
        done(t('error.invalid_user'))
      }
    } else {
      done(t('error.invalid_email'))
    }
  } else {
    done(t('error.no_payload'))
  }
}

export const user = promisify(_userObj)
